sudo: false
dist: trusty
language: php

services:
  - mysql
  - postgresql

php:
  - 5.6
  - 7
  - 7.1
  - 7.2

env:
  matrix:
    - DB=mysql
    - DB=sqlite
    - DB=pgsql

before_install:
  # copy sprinkles.json
  - cp app/sprinkles.example.json app/sprinkles.json
  # set up db
  - bash build/before_install.sh $DB
  # update node
  - nvm install 10.12.0

before_script:
  # install deps and UF
  - composer install
  - php bakery debug
  - php bakery build-assets
  - php bakery migrate

script:
  # run unit tests
  - app/vendor/bin/phpunit

after_failure:
  - cat app/log/userfrosting.log
