INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kathy',NULL,'321003',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brandy',NULL,'370901',NULL,NULL,'only works Mondays',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jane',NULL,'358001',NULL,NULL,'Retired (Filling in)',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sherri',NULL,'361101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carla',NULL,'358101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Paige',NULL,'357801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Debra',NULL,'362201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'369101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Christina',NULL,'364501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Chasidy',NULL,'362001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tamara',NULL,'347101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Gabriela',NULL,'349901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Wendy',NULL,'321401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Andrea',NULL,'344601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'351901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carrie',NULL,'311901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Pam',NULL,'325401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jenny',NULL,'370801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Inessa',NULL,'320106',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katarzyna','Katherine','305702',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'344502',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alyssa',NULL,'3446601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Teresa','Terri','342501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Erica',NULL,'341701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Gina',NULL,'341501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alyse',NULL,'313901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alyssa',NULL,'359101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Athina',NULL,'300401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carla',NULL,'330101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'330001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Marit',NULL,'330901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'357501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tiffney',NULL,'328701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'348001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carol',NULL,'328801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carleigh',NULL,'352301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Angie',NULL,'328301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'328501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kaitlyn',NULL,'368801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'310901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Joyce',NULL,'310801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brandy',NULL,'370902',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Shawn',NULL,'336401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Denise',NULL,'387501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('MacKenzie',NULL,'323501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Marcy',NULL,'323601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'354801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rita',NULL,'361303',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tiffany',NULL,'323001',NULL,NULL,'Dr Bova Tuesday only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'348102',NULL,NULL,'Dr Bova Tuesday only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'351501',NULL,NULL,'Dr Bova Tuesday only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Denise',NULL,'610001',NULL,NULL,'Dr Peterson',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heidi',NULL,'625201',NULL,NULL,'Dr. Daniels',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'621201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Aaron',NULL,'620801',NULL,'5/9/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Diane',NULL,'625801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Teresa',NULL,'619601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Courtney',NULL,'621101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nancy',NULL,'624201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jamie',NULL,'622601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stephanie',NULL,'624601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mindy',NULL,'606801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Morgan',NULL,'623101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tammy',NULL,'615701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stacey',NULL,'625501',NULL,'1/16/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sheila',NULL,'624901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Coral',NULL,'621801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'624401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Gina',NULL,'619101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittany',NULL,NULL,'1/30/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tara',NULL,'625401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kerri',NULL,'404001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jenn',NULL,'403301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lindsey',NULL,'403901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tera',NULL,'401401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amberlyn',NULL,'404701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Susan',NULL,'423301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'422701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jamie',NULL,'423501',NULL,NULL,'works T & Th only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'483302',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Laren',NULL,'483701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'480101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebbecca',NULL,'959801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'937701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Phung',NULL,'937601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'968302',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heather',NULL,'955504�',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katrina',NULL,'964401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nancy',NULL,'917201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Andrea',NULL,'946901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dina',NULL,'959601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Maria',NULL,'960401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittney',NULL,'967001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ali',NULL,'949213',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nataliya',NULL,'947001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lynn',NULL,'953301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheryl',NULL,'956801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'960501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittany',NULL,'967301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Megan',NULL,'967501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'957201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('JaSha',NULL,'964701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katheline',NULL,'969901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jan',NULL,'951901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jill',NULL,'929701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Theresa',NULL,'961001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Samantha',NULL,'958901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Elizabeth',NULL,'940901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alica',NULL,'928401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'928201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karri',NULL,'968801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Chris',NULL,'906903',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'967701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'941601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Beth',NULL,'941801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ann',NULL,'965001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alexis',NULL,'970301',NULL,'1/16/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Destiny',NULL,NULL,'2/2/2009',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittany',NULL,'924601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'964101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jane',NULL,'935501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carolyn','Carrie','935401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Janine',NULL,'935301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'967702',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'923502',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tracey',NULL,'960801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'968301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Schedule in Temp Chair Only',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Chelsey',NULL,'965301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'968101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Krissy',NULL,'956501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lindsey',NULL,'948201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Darcy',NULL,'912101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katherine',NULL,'912201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'918101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'918201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Holly',NULL,'967201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mary',NULL,'966201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kellie',NULL,'949601',NULL,'12/20/2018',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ashley',NULL,'902101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heather',NULL,'955502',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mary',NULL,'905401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessie',NULL,'965201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Bonnie','Lori','965901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('ReBecca','Becca','960502',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kait',NULL,'754601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heather',NULL,'753501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'754401',NULL,NULL,'Fridays only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ashley',NULL,'757401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'757201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Zala',NULL,'751401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'752001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kimberly',NULL,'756201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Holly',NULL,'146201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alyssa',NULL,'166201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Christina',NULL,'229002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stormie',NULL,'439505',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kristi',NULL,'291204',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brenda',NULL,'298201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amber',NULL,'228901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Wendy',NULL,'210901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jodi',NULL,'224701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Danielle','Dani','251406',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kari',NULL,'182701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jamie',NULL,'191001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kimberly',NULL,'175009',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Shirley',NULL,'124701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'154501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'195701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelsey',NULL,'440401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jody',NULL,'458301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Holly',NULL,'216101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ann',NULL,'441001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Colleen',NULL,'215801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katrina',NULL,'148301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rhea',NULL,'185701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES (NULL,NULL,NULL,NULL,NULL,'This clinic has NO HYGIENISTS, When scheduling look at the top of the schedule to see if a Temp Hygienist is listed. Example day to look at 1/31/19. If there is no one list PLEASE DO NOT SCHEDULE',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'177801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Leslie',NULL,'183203',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jodi',NULL,'451501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rianna',NULL,'438601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Temps filling the schedule',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sandy',NULL,'168001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicci',NULL,'168101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Maria',NULL,'144901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michelle',NULL,'151401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Molly',NULL,'151501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kimberly',NULL,'196801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Holly',NULL,'106901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittany',NULL,'124603',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'193002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Elizabeth',NULL,'134802',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'147106',NULL,'1/31/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Beth',NULL,'258101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'464801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Juliana',NULL,'877701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Knicole',NULL,'847001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mary',NULL,'259801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heidi',NULL,'433104',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alla',NULL,'455601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheryl',NULL,'459205',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'209601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Linda',NULL,'209603',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carol',NULL,'284601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Pat',NULL,'437501',NULL,'2/12/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'442001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brittany',NULL,'462201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'463401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'458401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Temp Agency',NULL,'880022',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lindsey',NULL,'236602',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Emma',NULL,'226201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carmen',NULL,'263002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Vicky',NULL,'226901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Martha',NULL,'204105',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kayla',NULL,'248708',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dawn',NULL,'297605',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kassie',NULL,'214602',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heidi',NULL,'255501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Chelsea',NULL,'203501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'200102',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stacy',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sara',NULL,'289501',NULL,NULL,'(blue) Dr. F,  Make sure all patients are scheduled with DDS they are treated planned with',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Aimee',NULL,'293007',NULL,NULL,'(blue) Dr. F,  Make sure all patients are scheduled with DDS they are treated planned with',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kathy',NULL,'244701',NULL,NULL,'(green) Dr. P,  Make sure all patients are scheduled with DDS they are treated planned with',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tania',NULL,'207701',NULL,NULL,'(green) Dr. P,  Make sure all patients are scheduled with DDS they are treated planned with',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Erika',NULL,'462501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Susan',NULL,NULL,'1/30/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Demi',NULL,'197501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Joanna',NULL,NULL,'10/16/2018',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,NULL,'2/5/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sharon',NULL,'100701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michelle',NULL,'112501',NULL,'4/26/2019','DO NOT SCHEDULE WITH MICHELLE',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jena','Gina','133901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Samantha',NULL,'183002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Joanna',NULL,'197502',NULL,NULL,'(FILL JOANNA SCHEDULE BEFORE SCHEDULING PT WITH TEMP UNTIL FURTHER NOTICE)',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mary',NULL,'464901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Destinee',NULL,'448102',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Megan',NULL,'285703',NULL,NULL,'Hygiene schedule MDE4 shouldn\'t be scheduled by the CEC on Thursdays. We only schedule SRP appointments in her schedule on Thursdays',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Morgan',NULL,'442101',NULL,NULL,'Hygiene schedule MDE4 shouldn\'t be scheduled by the CEC on Thursdays. We only schedule SRP appointments in her schedule on Thursdays',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'449101',NULL,NULL,'Hygiene schedule MDE4 shouldn\'t be scheduled by the CEC on Thursdays. We only schedule SRP appointments in her schedule on Thursdays',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Trinley',NULL,'101602',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Skyler',NULL,'198701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Andrea',NULL,'451301',NULL,NULL,'Using all Temp Hygienist,transfer SRP patients to the practice to be scheduled',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'457601',NULL,NULL,'Using all Temp Hygienist,transfer SRP patients to the practice to be scheduled',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jaime',NULL,'202901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Samantha',NULL,'289001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tiffany',NULL,'458601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'460801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jenee',NULL,'284101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brandi',NULL,'431301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tonia',NULL,'197901',NULL,'1/18/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Crystal',NULL,'186105',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Elizabeth',NULL,NULL,NULL,'1/31/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Samantha',NULL,'194101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heather',NULL,'221601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,'217103',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'206401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'205301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'254201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tennille',NULL,'438802',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Barbara',NULL,'435001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sarah',NULL,NULL,'2/12/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Angie',NULL,'103001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'103901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'194901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Terryl',NULL,'104203',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jean',NULL,'454401',NULL,NULL,'Only w Dr Meyer In blocks',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'203201',NULL,NULL,'Only w Dr Meyer In blocks',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Wendy',NULL,'204201',NULL,NULL,'Only w Dr Meyer In blocks',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Linda',NULL,'274307',NULL,NULL,'Only w Dr Meyer In blocks',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katherine',NULL,'443101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'166901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('RobinH',NULL,'167001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('RobinT',NULL,'175501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Celia',NULL,'187201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tia',NULL,'197601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Abigail',NULL,'163901',NULL,'3/15/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Hailee',NULL,'192201',NULL,NULL,'all NPIEs',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'257601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brooke',NULL,'222801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'231701',NULL,'12/31/2018','This is Now a Temp Chair',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Becky',NULL,'446601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nigora',NULL,'442201',NULL,'1/17/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katelyn',NULL,'458101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carrie',NULL,'223401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tricia',NULL,'278901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alisha',NULL,'290401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rachel',NULL,'459301',NULL,NULL,'DO NOT SCHEDULE APTS',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brandi',NULL,'461201',NULL,NULL,'DO NOT SCHEDULE APTS',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mary',NULL,'201401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ann',NULL,'206001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jocelyn',NULL,'291402',NULL,NULL,'Don\'t schedule with Jocelyn',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebekah',NULL,'460701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kristin',NULL,'227001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ashley',NULL,'455001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stacey',NULL,'459001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Christine',NULL,'257001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Meg',NULL,'220701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dawn',NULL,'452401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dolores',NULL,'849401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Gloria',NULL,'130001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cassidy',NULL,'185002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Susan',NULL,'199301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lynzie',NULL,NULL,'1/8/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Marie',NULL,'242501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Stephanie',NULL,'256301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Liana',NULL,'236005',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheri',NULL,'217601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Joelle',NULL,'210801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jocelyn',NULL,'291401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Natalie',NULL,'442301',NULL,'4/12',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Samantha',NULL,'456001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'213403',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Katie',NULL,'450601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Anne',NULL,'246102',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'298501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelli',NULL,'447701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Terryl',NULL,'104201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ciara',NULL,'196901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Miranda',NULL,'277601',NULL,NULL,'All Kaminski',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kembria',NULL,'253201',NULL,NULL,'All Kaminski',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Myranda',NULL,'437101',NULL,NULL,'Longe',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Joanne',NULL,'463901',NULL,NULL,'Longe',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Heather',NULL,'298108',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'294813',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dayna',NULL,'299208',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Peggy',NULL,'162701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kim',NULL,'162801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Shaylah',NULL,'185101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'233204',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheryl',NULL,'207201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheryl',NULL,'233801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ann',NULL,'441002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Felisha',NULL,'430901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rita',NULL,'192701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Laura',NULL,'286901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Bernadette',NULL,'253901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carry',NULL,'218001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rachel',NULL,'206901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jessica',NULL,'229504',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelly',NULL,'449102',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Bobbie',NULL,'140103',NULL,NULL,'Dr Lang Team',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Hillary',NULL,'184401',NULL,NULL,'Dr Lang Team',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'197704',NULL,NULL,'Dr Lang Team',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sam',NULL,'181603',NULL,NULL,'Dr Charging Team',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lynn',NULL,'109201',NULL,NULL,'Dr Charging Team',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Holly',NULL,NULL,NULL,NULL,'Regional Float Hygienist',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jennifer',NULL,'454801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'438301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brandi',NULL,'431302',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ashley',NULL,'162103',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Emily',NULL,'176701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'190801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brenda',NULL,'453001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cassie',NULL,'224901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Temp Hygienist',NULL,'800005',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Megan',NULL,'188801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Diana',NULL,'156703',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sara',NULL,'189702',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Emily',NULL,'184501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'434402',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sara',NULL,'189701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Makayla',NULL,NULL,'2/25/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Christa',NULL,'866601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'860901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sheri',NULL,'862301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lachan',NULL,'827301','2/11/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Taylor',NULL,'820001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michelle',NULL,'864001',NULL,NULL,'Mon, Tue, Wed, Thurs',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kerin',NULL,'866101',NULL,NULL,'Tuesday, Wed, Thurs',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tina',NULL,'867301',NULL,NULL,'Mondays Only',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Darlynn',NULL,'865001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tammie',NULL,'876101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tamara',NULL,'865101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lynette',NULL,'838001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tina',NULL,'838501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'832001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'836101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Elizabeth','Liz','836401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michele',NULL,'834001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Danielle',NULL,'829001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kristen',NULL,'835201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lori',NULL,'833001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Diana',NULL,'832401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Aubrey',NULL,'839401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Deanna',NULL,'824001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Regina',NULL,'898001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mickey',NULL,'878301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Vanna',NULL,'826101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sandy',NULL,'897501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Beth',NULL,'258101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'464801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('JulIana',NULL,'877701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Knicole',NULL,'847001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lori',NULL,'870701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'870801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rebecca',NULL,'872801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Angela',NULL,'892601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Barbara',NULL,'892301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicole',NULL,'892201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cortney',NULL,'892501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alexis',NULL,'892501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sandy',NULL,'168001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Nicci',NULL,'168101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Chrissie',NULL,'877101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tiffany',NULL,'841601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Boisera',NULL,NULL,'3/5/2019',NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brigitte',NULL,'893501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Abigail','Abby','879801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tamara','Tammy','894001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tonia',NULL,'858901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michelle',NULL,'826201',NULL,NULL,'DO NOT schedule with Michelle',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Diane',NULL,'848101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Donna',NULL,'848201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Paige',NULL,'848001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Meg',NULL,'220701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dawn',NULL,'452401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dolores',NULL,'849401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'850901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Ruth',NULL,'851201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mandy',NULL,'827001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Abby',NULL,'858701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mikayla',NULL,'847301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Melissa',NULL,'857901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sheree',NULL,'852701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Rachel',NULL,'843501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Donna',NULL,'848202',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Carol',NULL,'673101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amy',NULL,'673001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dorie',NULL,'671201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'671301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sheila',NULL,'675301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Alyssa',NULL,'675001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Janet',NULL,'678901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Amanda',NULL,'668501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Elizabeh','Betsy','670401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Laura',NULL,'670301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Julie',NULL,'676101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'676201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Dana',NULL,'676501',NULL,'12/5/2018',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lisa',NULL,'676601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tracey',NULL,'676701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Linda',NULL,'663901',NULL,'1/17/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kerri',NULL,'653901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kristen',NULL,'653801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Gilmari',NULL,'6572',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Natalie',NULL,'6533',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Allison',NULL,'6636',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelley',NULL,'663001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('William',NULL,'662601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sue',NULL,'652201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tammie',NULL,'662401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Michele',NULL,'651201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lynn',NULL,'651301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Beth',NULL,'651801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cindy',NULL,'687002',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Kelsey',NULL,'680401',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Barbara',NULL,'682101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tammy',NULL,'682001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Donna',NULL,'685201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Betsey',NULL,'786201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('LeAnne',NULL,'796901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Anna',NULL,'779301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Shannon',NULL,'777501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Mackenzie',NULL,'778401',NULL,'2/14/2019',NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Pamela',NULL,'780501',NULL,NULL,'Do Not Schedule any appointments before 9/1/19',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Patricia',NULL,'782401',NULL,NULL,'Do Not Schedule any appointments before 9/1/19',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('ElsieMarie',NULL,'785701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('CatherineL',NULL,'785301',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Victoria',NULL,'785901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('CatherineD',NULL,'778902',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Tracy',NULL,'788101',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karen',NULL,'783201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Lorraine',NULL,'781801',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Angela',NULL,'781901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jana',NULL,'709201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Darcy',NULL,'711601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Cheryl',NULL,'711001',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Sharon',NULL,'711501',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Myrna',NULL,'801901',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Karin',NULL,'814201',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Jolene',NULL,'801701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Loretta',NULL,'808601',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Raquel',NULL,'808701',NULL,NULL,NULL,1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Erin',NULL,'807301',NULL,NULL,'Do Not Schedule in FRM_2 she retired',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Victoria',NULL,'813501',NULL,NULL,'Do Not Schedule in FRM_2 she retired',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('TaRee',NULL,'814701',NULL,NULL,'Do Not Schedule in FRM_2 she retired',1);
INSERT INTO hygienist_details(name,nickname,provider_num,start_date,end_date,notes,status_id) VALUES ('Brenda',NULL,'803902',NULL,NULL,'Do Not Schedule in FRM_2 she retired',1);
